# Generated by Django 5.2.7 on 2025-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期日')], unique=True, verbose_name='星期')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='開店時間')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='打烊時間')),
                ('is_closed', models.BooleanField(default=False, verbose_name='本日休息')),
            ],
            options={
                'verbose_name': '診所營業時間',
                'verbose_name_plural': '診所營業時間',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='牙醫姓名')),
                ('description', models.TextField(help_text='請輸入醫生的詳細介紹', verbose_name='牙醫描述')),
            ],
            options={
                'verbose_name': '牙醫資料',
                'verbose_name_plural': '牙醫資料',
            },
        ),
    ]
