# Generated by Django 5.2.7 on 2025-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinichours',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='clinichours',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='clinichours',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='clinichours',
            name='afternoon',
            field=models.BooleanField(default=True, verbose_name='午 (14:30-17:30)'),
        ),
        migrations.AddField(
            model_name='clinichours',
            name='evening',
            field=models.BooleanField(default=True, verbose_name='晚 (18:30-21:00)'),
        ),
        migrations.AddField(
            model_name='clinichours',
            name='morning',
            field=models.BooleanField(default=True, verbose_name='早 (09:30-12:00)'),
        ),
    ]
