# Generated by Django 5.2.7 on 2025-12-09 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_clinichours_closing_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='症狀名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '看診問題設定',
                'verbose_name_plural': '看診問題設定',
            },
        ),
        migrations.AlterModelOptions(
            name='clinichours',
            options={'ordering': ['day_of_week'], 'verbose_name': '診所營業時間與上限', 'verbose_name_plural': '診所營業時間與上限'},
        ),
        migrations.AddField(
            model_name='clinichours',
            name='afternoon_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='午診上限'),
        ),
        migrations.AddField(
            model_name='clinichours',
            name='evening_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='晚診上限'),
        ),
        migrations.AddField(
            model_name='clinichours',
            name='morning_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='早診上限'),
        ),
        migrations.AlterField(
            model_name='clinichours',
            name='afternoon',
            field=models.BooleanField(default=True, verbose_name='午診 (14:30-17:30)'),
        ),
        migrations.AlterField(
            model_name='clinichours',
            name='evening',
            field=models.BooleanField(default=True, verbose_name='晚診 (18:30-21:00)'),
        ),
        migrations.AlterField(
            model_name='clinichours',
            name='morning',
            field=models.BooleanField(default=True, verbose_name='早診 (09:30-12:00)'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='看診日期')),
                ('time_slot', models.CharField(choices=[('morning', '早診'), ('afternoon', '午診'), ('evening', '晚診')], max_length=20, verbose_name='時段')),
                ('patient_type', models.CharField(choices=[('new', '初診'), ('return', '複診')], max_length=10, verbose_name='初/複診')),
                ('registration_number', models.PositiveIntegerField(verbose_name='掛號號碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='掛號會員')),
                ('symptoms', models.ManyToManyField(to='clinic.symptom', verbose_name='主訴問題')),
            ],
            options={
                'verbose_name': '掛號紀錄',
                'verbose_name_plural': '掛號紀錄',
                'unique_together': {('user', 'date', 'time_slot')},
            },
        ),
    ]
