# Generated by Django 5.2.7 on 2025-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.CharField(default='', max_length=10, verbose_name='身分證字號'),
        ),
    ]
