# Generated by Django 5.2.7 on 2025-12-13 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClinicState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('time_slot', models.CharField(choices=[('morning', '早診'), ('afternoon', '午診'), ('evening', '晚診')], max_length=20, verbose_name='時段')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='目前叫號')),
            ],
            options={
                'verbose_name': '每日診次叫號狀態',
                'verbose_name_plural': '每日診次叫號狀態',
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
