# Generated by Django 5.2.7 on 2025-12-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_dailyclinicstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='請更新診所地址', max_length=200, verbose_name='診所地址')),
                ('phone', models.CharField(default='02-1234-5678', max_length=50, verbose_name='聯絡電話')),
            ],
            options={
                'verbose_name': '診所基本資訊',
                'verbose_name_plural': '診所基本資訊',
            },
        ),
    ]
