# Generated by Django 5.2.7 on 2025-12-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_clinicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='習慣調查題目')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '用牙習慣設定',
                'verbose_name_plural': '用牙習慣設定',
            },
        ),
        migrations.AlterField(
            model_name='dailyclinicstate',
            name='time_slot',
            field=models.CharField(max_length=20, verbose_name='時段'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='habits',
            field=models.ManyToManyField(blank=True, to='clinic.dentalhabit', verbose_name='用牙習慣'),
        ),
    ]
