# Generated by Django 5.2.7 on 2025-12-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_dentalhabit_alter_dailyclinicstate_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='habits',
        ),
        migrations.AddField(
            model_name='dentalhabit',
            name='max_label',
            field=models.CharField(default='非常同意', max_length=50, verbose_name='選項7代表(如:非常同意)'),
        ),
        migrations.AddField(
            model_name='dentalhabit',
            name='min_label',
            field=models.CharField(default='非常不同意', max_length=50, verbose_name='選項1代表(如:非常不同意)'),
        ),
        migrations.CreateModel(
            name='AppointmentHabitResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='評分(1-7)')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.dentalhabit')),
            ],
            options={
                'unique_together': {('appointment', 'habit')},
            },
        ),
    ]
