# Generated by Django 5.2.7 on 2025-12-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_remove_appointment_habits_dentalhabit_max_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='habits',
            field=models.ManyToManyField(blank=True, through='clinic.AppointmentHabitResponse', to='clinic.dentalhabit', verbose_name='用牙習慣調查結果'),
        ),
    ]
