# Generated by Django 5.2.7 on 2025-12-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_appointment_habits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='問題內容')),
                ('unit', models.CharField(blank=True, help_text='例如：次/天、年、支', max_length=20, null=True, verbose_name='單位')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '連續資料問題設定',
                'verbose_name_plural': '連續資料問題設定',
            },
        ),
        migrations.CreateModel(
            name='AppointmentContinuousResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='數值')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.continuoushabit')),
            ],
            options={
                'unique_together': {('appointment', 'question')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='continuous_data',
            field=models.ManyToManyField(blank=True, through='clinic.AppointmentContinuousResponse', to='clinic.continuoushabit', verbose_name='連續資料調查結果'),
        ),
    ]
