# Generated by Django 5.2.7 on 2025-12-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_continuoushabit_appointmentcontinuousresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinichours',
            name='afternoon_time',
            field=models.CharField(default='14:00-17:30', max_length=50, verbose_name='午診時間'),
        ),
        migrations.AddField(
            model_name='clinichours',
            name='evening_time',
            field=models.CharField(default='18:30-21:00', max_length=50, verbose_name='晚診時間'),
        ),
        migrations.AddField(
            model_name='clinichours',
            name='morning_time',
            field=models.CharField(default='09:00-12:00', max_length=50, verbose_name='早診時間'),
        ),
        migrations.AlterField(
            model_name='clinichours',
            name='afternoon',
            field=models.BooleanField(default=True, verbose_name='午診開關'),
        ),
        migrations.AlterField(
            model_name='clinichours',
            name='evening',
            field=models.BooleanField(default=True, verbose_name='晚診開關'),
        ),
        migrations.AlterField(
            model_name='clinichours',
            name='morning',
            field=models.BooleanField(default=True, verbose_name='早診開關'),
        ),
    ]
