# Generated by Django 5.2.7 on 2025-12-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_clinichours_afternoon_time_clinichours_evening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='slogan_content',
            field=models.TextField(default='我們提供最專業的牙科服務，守護您與家人的口腔健康。線上預約，輕鬆看診。', verbose_name='首頁副標題'),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='slogan_title',
            field=models.CharField(default='微笑，從這裡開始', max_length=100, verbose_name='首頁大標題'),
        ),
    ]
