# Generated by Django 5.2.7 on 2025-12-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_clinicinfo_slogan_content_clinicinfo_slogan_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='手機號碼'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='real_name',
            field=models.CharField(default='', max_length=50, verbose_name='真實姓名'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.CharField(max_length=10, verbose_name='身分證字號'),
        ),
        migrations.AlterField(
            model_name='continuoushabit',
            name='unit',
            field=models.CharField(blank=True, help_text='例如：次/天', max_length=20, null=True, verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='dentalhabit',
            name='max_label',
            field=models.CharField(default='非常同意', max_length=50, verbose_name='選項7代表'),
        ),
        migrations.AlterField(
            model_name='dentalhabit',
            name='min_label',
            field=models.CharField(default='非常不同意', max_length=50, verbose_name='選項1代表'),
        ),
    ]
