# Generated by Django 5.2.7 on 2025-12-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_remove_appointment_patient_type_appointment_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='年齡'),
        ),
    ]
