# Generated by Django 5.2.7 on 2025-12-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_remove_appointment_phone_appointment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='是否顯示在總表'),
        ),
    ]
