# Generated by Django 5.2.7 on 2025-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_appointment_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(db_index=True, unique=True, verbose_name='原始掛號ID')),
                ('user_id', models.IntegerField(verbose_name='會員ID')),
                ('user_username', models.CharField(blank=True, max_length=150, verbose_name='會員帳號')),
                ('date', models.DateField(verbose_name='看診日期')),
                ('time_slot', models.CharField(choices=[('morning', '早診'), ('afternoon', '午診'), ('evening', '晚診')], max_length=20, verbose_name='時段')),
                ('real_name', models.CharField(default='', max_length=50, verbose_name='真實姓名')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='年齡')),
                ('patient_id', models.CharField(max_length=10, verbose_name='身分證字號')),
                ('symptoms_text', models.TextField(blank=True, help_text='以逗號分隔的症狀名稱', verbose_name='主訴問題')),
                ('habits_data', models.TextField(blank=True, help_text='JSON 格式：{habit_id: score}', verbose_name='用牙習慣調查結果')),
                ('continuous_data', models.TextField(blank=True, help_text='JSON 格式：{question_id: value}', verbose_name='連續資料調查結果')),
                ('registration_number', models.PositiveIntegerField(verbose_name='掛號號碼')),
                ('created_at', models.DateTimeField(verbose_name='建立時間')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否顯示在總表')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='最後同步時間')),
            ],
            options={
                'verbose_name': 'DID 看診資料總表',
                'verbose_name_plural': 'DID 看診資料總表',
                'db_table': 'clinic_did',
                'managed': True,
                'indexes': [models.Index(fields=['appointment_id'], name='clinic_did_appoint_ce5b4a_idx'), models.Index(fields=['date', 'time_slot'], name='clinic_did_date_4db079_idx'), models.Index(fields=['patient_id'], name='clinic_did_patient_1a0c23_idx')],
            },
        ),
    ]
